<script>
export default {
  name: 'HomePage',
  data() {
    return {
      highlights: [
        {
          title: 'Any topic, any language',
          body: 'Drop in up to three prompts and let the AI craft bespoke trivia.'
        },
        {
          title: '9-round streaks',
          body: 'Sprint through fast-paced questions with a live progress tracker.'
        },
        {
          title: 'Adaptive difficulty',
          body: 'Pick a mood-from Friendly warm-ups to Immortal challenges.'
        }
      ],
      steps: [
        'Sign up or log in to sync your streaks.',
        'Pick three topics and a difficulty badge.',
        'Race the timer, rack up points, brag to friends.'
      ]
    };
  },
  methods: {
    startPlaying() {
      this.$router.push('/create');
    },
    goToLogin() {
      this.$router.push('/login');
    }
  }
};
</script>

<template>
  <div class="home">
    <section class="hero">
      <div class="hero-copy">
        <p class="eyebrow">Ready. Set. Quiz.</p>
        <h1>Trivia that adapts to you.</h1>
        <p class="lead">Feed the generator anything you love-games, anime, history, niches-and race against a cinematic countdown.</p>
        <div class="hero-ctas">
          <button class="primary" @click="startPlaying">Start a run</button>
          <button class="secondary" @click="goToLogin">Log in</button>
        </div>
        <div class="stats">
          <div>
            <span class="stat-number">15s</span>
            <span class="stat-label">per question</span>
          </div>
          <div>
            <span class="stat-number">3</span>
            <span class="stat-label">topics at once</span>
          </div>
          <div>
            <span class="stat-number">5</span>
            <span class="stat-label">difficulty tiers</span>
          </div>
        </div>
      </div>
      <div class="hero-card">
        <p class="card-title">How it works</p>
        <ol>
          <li v-for="(step, idx) in steps" :key="idx">{{ step }}</li>
        </ol>
        <p class="note">Answers are generated by AI-double-check before you flex those bragging rights.</p>
      </div>
    </section>

    <section class="grid">
      <article class="grid-card" v-for="(highlight, index) in highlights" :key="index">
        <h3>{{ highlight.title }}</h3>
        <p>{{ highlight.body }}</p>
      </article>
    </section>
  </div>
</template>

<style scoped>
.home {
  display: flex;
  flex-direction: column;
  gap: 2.5rem;
}

.hero {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(260px, 1fr));
  gap: 2rem;
  align-items: center;
}

.hero-copy h1 {
  font-size: clamp(2rem, 4vw, 3.6rem);
  margin-bottom: 0.75rem;
}

.lead {
  color: var(--text-muted);
  font-size: 1.1rem;
  max-width: 32ch;
}

.eyebrow {
  text-transform: uppercase;
  font-size: 0.85rem;
  letter-spacing: 0.3em;
  color: var(--accent);
  margin-bottom: 0.75rem;
}

.hero-ctas {
  display: flex;
  gap: 1rem;
  margin: 1.5rem 0;
}

button.primary,
button.secondary {
  border-radius: 999px;
  padding: 0.85rem 1.8rem;
  border: none;
  font-weight: 600;
  transition: transform 0.2s ease, box-shadow 0.2s ease;
}

button.primary {
  background: linear-gradient(120deg, var(--accent), var(--accent-2));
  color: #05060f;
  box-shadow: 0 15px 30px rgba(12, 200, 255, 0.35);
}

button.secondary {
  background: transparent;
  border: 1px solid var(--panel-border);
  color: var(--text-primary);
}

button.primary:hover,
button.secondary:hover {
  transform: translateY(-2px);
}

.stats {
  display: flex;
  gap: 1.5rem;
  margin-top: 1.25rem;
}

.stat-number {
  font-size: 2rem;
  font-weight: 700;
  display: block;
}

.stat-label {
  color: var(--text-muted);
  font-size: 0.9rem;
}

.hero-card {
  background: linear-gradient(160deg, rgba(18, 199, 255, 0.25), rgba(168, 85, 247, 0.12));
  border-radius: 24px;
  padding: 1.75rem;
  border: 1px solid var(--panel-border);
}

.card-title {
  text-transform: uppercase;
  font-size: 0.85rem;
  letter-spacing: 0.2em;
  margin-bottom: 1rem;
  color: var(--text-muted);
}

.hero-card ol {
  padding-left: 1.25rem;
  display: flex;
  flex-direction: column;
  gap: 0.75rem;
}

.hero-card li {
  font-size: 1rem;
}

.note {
  margin-top: 1.5rem;
  color: var(--text-muted);
  font-size: 0.9rem;
}

.grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
  gap: 1.5rem;
}

.grid-card {
  padding: 1.5rem;
  border-radius: 20px;
  background: rgba(255, 255, 255, 0.02);
  border: 1px solid var(--panel-border);
}

.grid-card h3 {
  margin-bottom: 0.5rem;
}

.grid-card p {
  color: var(--text-muted);
}

@media (max-width: 640px) {
  .hero-ctas {
    flex-direction: column;
    align-items: stretch;
  }

  .stats {
    flex-wrap: wrap;
  }
}
</style>
